### PR TITLE
bluez 5.44

### PR DESCRIPTION
**Pull request by CromFr**
Following bluez dbus api change

cf issue #7

### CODE REVIEW

**Comment by CromFr** [comment]
This currently works only for GATTCharacteristic::write_value, and flags argument is poorly handled.

The flags argument of write_value should be an array of `MessageItem::DictEntry(MessageType::Str, MessageType::Variant)`, but it feels wrong to me to expose underlying dbus-rs types, so I used a `HashMap<&str,&str>` to be able to build & test.

What should I do for this?

**Comment by dati91** [comment]
Thanks for looking into this!

Yes, you shouldn't expose the dbus types.

It seems that only 3 possible options are valid: 1) Empty dict 2) "offset" with value 3) "device" with object (of course the 2. and 3. can be together)
The third one is only available for server side, so I don't think we should worry about that for now.
We should handle the offset value, which can be an `Option<u16>` (the default(`None`) will be `0`).

You can add the dict somewhat like this:
```
self.call_method("WriteValue",
                 Some(&[MessageItem::new_array(args).unwrap(),
                        MessageItem::DictEntry(Box::new("offset".into()),
                                               Box::new(offset.unwrap_or(0u16).into()))]))
```

Also you need to update the `read_value` calls as well.
```
let mut m = /* method call */
m.append_items([/* Dict as above */]);
```

**Comment by CromFr** [comment]
I changed the HashMap parameter in favor to your offset solution, but handled it a bit differently so that an empty Dict is sent to dbus if offset is None.

I'll test it on my BLE lightbulb later this week, to check if everything works as expected

The dbus GATT Descriptor interface has also changed the same way: https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n165

I'll change the Descriptor too if you're ok with my current code ;)

**Comment by dati91** [comment]
Seems OK to me. Let me now if you tested it.

**Comment by CromFr** [comment]
I just tested it with my lightbulb, and it looks ok for me.

I think you should test on another device before merging, because I could not get the offset parameter to work with mine since it has a weird implementation of GATT (the value read for a characteristic is different from the value written)

**Comment by zakorgy** [comment]
@CromFr sorry for being late. I looked trough your changes, and tested on different devices. The `read_value` calls need some correction to work well with the offset parameter, and the indentation is slipped in some places. Here is a [diff](https://gist.github.com/zakorgy/a4c07f9e3b6e91585a9e1392c5f38827) with the mentioned changes, which I put together during the tests, and applies to your work. Squash your commits, so we can merge this PR.
Thanks for working on this!

**Comment by CromFr** [comment]
here it is

hope everything is good ;)

**Comment by zakorgy** [comment]
Thx @CromFr

**Pull request merged**
