### PR TITLE
Update API

### PR DESCRIPTION
**Pull request by jamesmunns**
Hey @szeged, I found your library, and it looks really great!

I wanted to share some of the things I've been doing in my crates to provide a simpler API to use. The three major things I did:

- Use error_chain instead of Boxed errors to reduce Heap allocations
- Expose simpler names for internal components, to make items easier to `use` in dependent crates
- Run Rustfmt, including the `try!()` to `?` converter

Please let me know what you think. I'd like to contribute back any of the changes I make while working on my project (hopefully just adding functionality after this)

### CODE REVIEW

**Review by akosthekiss — COMMENTED** [review]
I'm not the project owner, not even a contributor, only the maintainer of a sibling project, so take my comment with a grain of salt. But:
- Changing the API (return value of functions, name of published types) is to be done with care as it should be coordinated between the Devices crate and this one at the very least, but preferably between even two more crates (BlurDroid and BlurMac).
- Let the project owner bump the version when and as they see fit.
- Please, add LFs at EOFs.

**Comment by jamesmunns** [comment]
@akosthekiss Thanks for the input! I was not aware of BlurDroid or BlurMac, so I will look into that.

I revved the crate version number because I was introducing breaking API changes. I am happy to revert this, however it will likely be necessary for the reasons that you mentioned (breaking other crates). I'll wait for comments from @szeged on this.

I have added LFs on EOFs.

If you have any other comments, I am happy to have input. Thanks again!

**Comment by jamesmunns** [comment]
Hey @akosthekiss, I just realized that @szeged is the organization for the University of Szeged. Apologies for my lack of awareness :). If you have suggestions for a maintainer for this project I could reach out to, I would appreciate it! I also did not realize this was part of a larger, active project, being integrated into Servo. Thanks again for the pointers to the other crates, it helped a lot to get context.

I would be happy to submit PRs for the other projects as well. If all the implementation crates are expected to expose the same API, do you think it would make sense to have a shared `Blur-Trait` crate, which could make that API more clear? I believe that might also help to simplify some of the code in https://github.com/servo/devices/blob/master/src/bluetooth.rs, though I have not investigated too deeply yet.

Let me know what you think, and thanks again for the comments.

**Comment by dati91** [comment]
Hi @jamesmunns 
Sorry for my late reply!

First of all, thanks for the interest.
Yes, this is part of [Servo](https://servo.org/)'s [WebBluetooth implementation](https://szeged.github.io/servo/), which requires multi-platform support.
There are 3+1 platforms supported currently: linux ([blurz](https://crates.io/crates/blurz)), android ([blurdroid](https://crates.io/crates/blurdroid)), macOS ([blurmac](https://crates.io/crates/blurmac)), and a testing related ([blurmock](https://crates.io/crates/blurmock)). And the windows implementation is in plans (maybe blurwin?).
The crate which holds everything together is servo's [device crate](https://github.com/servo/devices). As time passed it got a little bit out of control as you noticed, so a shared `Blur-Trait` would make sense.
There is [an issue about this](https://github.com/servo/devices/issues/21), which is up for grabs at the moment if you are interested.

About the PR,
The rustfmt cleanup: great!
I like the other two as well, but that part is a little bit trickier. If you are interested in the issue mentioned above, than we can talk about a larger scale API change.
If not, than let me ask you to separate the changes into commits, that represent the 3 things you did. Also the revision bump should be a separate commit to make life easier with the cargo crate publish.

Let me know what you think!

**Comment by jamesmunns** [comment]
Hey @dati91, I'll see if I can put some time into a `Blur-Trait` crate, as well as a larger refactor this weekend. If it goes well, I will open up other branches to submit the PR, otherwise I will separate my current work into multiple Commits/PRs.

Thanks for the feedback!

**Comment by dati91** [comment]
Great!
Let me know if you have any question.

**Comment by dati91** [comment]
I'm closing this because of inactivity.

**Pull request closed without merging**
